# Generated by Django 4.2.4 on 2023-09-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_producthistory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='entry',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('substract', 'substract')], max_length=60),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productHistory', to='administration.product'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
