# Generated by Django 4.2.4 on 2023-09-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_producthistory_entry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='qty',
            new_name='editQty',
        ),
    ]
