# Generated by Django 4.2.4 on 2023-10-08 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_rename_qty_producthistory_editqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 17, 43, 38, 298547)),
        ),
    ]
