# Generated by Django 4.2.4 on 2023-10-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_contactform_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendServices',
        ),
    ]
