# Generated by Django 4.2.4 on 2023-10-12 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_frontendbanner_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendbanner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 0, 0, 5, 973634)),
        ),
    ]
