# Generated by Django 4.2.4 on 2023-10-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_frontendbanner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendbanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
