# Generated by Django 4.2.4 on 2024-06-04 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_frontendbanner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productHistoryEmail', to=settings.AUTH_USER_MODEL),
        ),
    ]
