# Generated by Django 4.2.4 on 2024-06-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_producthistory_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='email',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productHistoryName', to='administration.accountprofiles'),
        ),
    ]
