# Generated by Django 4.2.4 on 2025-01-11 07:35

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='productImages/', validators=[administration.models.validate_image_size]),
        ),
    ]
