# Generated by Django 4.2.4 on 2023-09-24 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('annual_leave', models.FloatField(default=0.0)),
                ('childcare_leave', models.FloatField(default=0.0)),
                ('maternity_leave', models.FloatField(default=0.0)),
                ('paternity_leave', models.FloatField(default=0.0)),
                ('sick_leave', models.FloatField(default=0.0)),
                ('upaid_leave', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('leave_type', models.CharField(choices=[('annual leave', 'annual leave'), ('childcare leave', 'childcare leave'), ('meternity leave', 'maternity leave'), ('paternity leave', 'paternity leave'), ('sick leave', 'sick leave'), ('unpaid leave', 'unpaid leave')], max_length=200)),
                ('entry', models.CharField(blank=True, choices=[('add', 'add'), ('substract', 'substract')], max_length=150)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employeeLeaveHistory/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('qty', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=88)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('employeeLeave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeleave')),
            ],
        ),
    ]
