# Generated by Django 4.2.4 on 2023-09-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_upaid_leave_employeeleave_unpaid_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavehistory',
            name='employeeLeave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeLeaveHistroy', to='employee.employeeleave'),
        ),
        migrations.AlterField(
            model_name='employeeleavehistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavehistory',
            name='leave_type',
            field=models.CharField(choices=[('annual leave', 'annual leave'), ('childcare leave', 'childcare leave'), ('maternity leave', 'maternity leave'), ('paternity leave', 'paternity leave'), ('sick leave', 'sick leave'), ('unpaid leave', 'unpaid leave')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeleavehistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavehistory',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=88),
        ),
    ]
