# Generated by Django 4.2.4 on 2023-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeleavehistory_employeeleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFrontendProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='employeeFrontendProfile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
