# Generated by Django 4.2.4 on 2023-10-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeefrontendprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefrontendprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
