# Generated by Django 4.2.4 on 2023-10-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeefrontendprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefrontendprofile',
            name='employee_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
