# Generated by Django 4.2.4 on 2023-08-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleServices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('hair', 'hair'), ('beauty', 'beauty'), ('health', 'health')], max_length=200)),
                ('service_name', models.CharField(max_length=220)),
                ('service_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='serviceimages/')),
                ('sale_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.saleservices')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grand_total', models.FloatField(default=0.0)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('paynow', 'paynow'), ('creditcard', 'credit card'), ('nets', 'nets'), ('grab', 'grab'), ('package', 'package'), ('instorecredit', 'in store credit'), ('refund', 'refund')], max_length=200)),
                ('personal_remarks', models.TextField()),
                ('customer_remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.credithistory')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administration.accounts')),
                ('voucher_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.voucherhistory')),
            ],
        ),
        migrations.AddField(
            model_name='saleservices',
            name='sales_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.salestransaction'),
        ),
    ]
