# Generated by Django 4.2.4 on 2023-08-30 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_packagehistory_remove_voucherhistory_voucher_and_more'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='voucher_history',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='package_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.packagehistory'),
        ),
    ]
