# Generated by Django 4.2.4 on 2023-10-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_saleservices_sales_transaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceImages',
        ),
    ]
