# Generated by Django 4.2.4 on 2023-08-30 03:54

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', jsignature.fields.JSignatureField()),
            ],
        ),
        migrations.RemoveField(
            model_name='voucherhistory',
            name='voucher',
        ),
        migrations.RenameModel(
            old_name='Voucher',
            new_name='Package',
        ),
    ]
