# Generated by Django 4.2.4 on 2023-08-30 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_salestransaction_voucher_history_and_more'),
        ('customer', '0002_packagehistory_remove_voucherhistory_voucher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherHistory',
        ),
        migrations.AddField(
            model_name='packagehistory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.package'),
        ),
    ]
