# Generated by Django 4.2.4 on 2023-09-13 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_credithistory_entry_packagehistory_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
