# Generated by Django 4.2.4 on 2023-09-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_credithistory_customer_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
