# Generated by Django 4.2.4 on 2023-09-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customernotes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotes',
            name='customer_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerNotes', to='customer.customerprofile'),
        ),
    ]
