# Generated by Django 4.2.4 on 2023-09-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customernotes_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credithistory',
            name='customer_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditHistory', to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='package',
            name='customer_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='package',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageHistory', to='customer.package'),
        ),
    ]
