# Generated by Django 4.2.4 on 2023-09-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_credithistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='balanceQty',
            field=models.IntegerField(),
        ),
    ]
