# Generated by Django 4.2.4 on 2023-09-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_package_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='balanceQty',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='customer.customerprofile'),
        ),
    ]
