# Generated by Django 4.2.4 on 2024-12-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_credithistory_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=150),
        ),
    ]
